Task 8
AT20-DevOps/AT20_CONVERT_SERVICE pull request #12
Opened 2023-05-29 22:40 UTC by CarolinaZegarra01

2023-05-29 22:40 UTC, CarolinaZegarra01 commented
![image](https://github.com/AT20-DevOps/AT20_CONVERT_SERVICE/assets/126516590/fc70b15f-9a31-4372-a160-4a3ac86da1fe)

2023-05-29 23:39 UTC, CarolinaZegarra01 commented
![image](https://github.com/AT20-DevOps/AT20_CONVERT_SERVICE/assets/126516590/f0ef2223-d842-4671-a3eb-7c8bab62190f)

2023-06-01 12:47 UTC, vcarmen requested changes
Add the stage to deploy to AUTO remotely

2023-06-01 13:01 UTC, vcarmen approved these changes

2023-06-01 13:01 UTC, merged