Task 8 : Add the stage to deploy to Dev
AT20-DevOps/AT20_CONVERT_SERVICE pull request #13
Opened 2023-05-29 23:14 UTC by daniish77

![image](https://github.com/AT20-DevOps/AT20_CONVERT_SERVICE/assets/117138801/e4ca2637-1684-40bf-b0c3-70ab2168e863)

2023-05-29 23:26 UTC, daniish77 commented
![image](https://github.com/AT20-DevOps/AT20_CONVERT_SERVICE/assets/117138801/69daa8cf-941b-43b0-ac6b-8451451f7a9e)

2023-05-29 23:26 UTC, daniish77 commented
![image](https://github.com/AT20-DevOps/AT20_CONVERT_SERVICE/assets/117138801/d0030020-caa7-4077-a518-e76c635dfedc)

2023-06-01 12:48 UTC, vcarmen requested changes
Add the stage to deploy to AUTO remotely

2023-06-01 13:01 UTC, vcarmen approved these changes

2023-06-01 15:28 UTC, merged